-- Create database (if not exists)
CREATE DATABASE IF NOT EXISTS CORTEX_FEEDBACK_DB;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS CORTEX_FEEDBACK_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS CORTEX_FEEDBACK_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS CORTEX_FEEDBACK_DB.GOLD;
