-- BRONZE: Raw feedback
CREATE OR REPLACE TABLE CORTEX_FEEDBACK_DB.BRONZE.FEEDBACK_RAW (
    RAW_TEXT STRING,
    RATING NUMBER(2,1),
    SOURCE STRING,
    CREATED_AT TIMESTAMP_NTZ
);

-- SILVER: Cleaned feedback
CREATE OR REPLACE TABLE CORTEX_FEEDBACK_DB.SILVER.FEEDBACK_CLEAN (
    FEEDBACK_ID STRING,
    CLEAN_TEXT STRING,
    RATING NUMBER(2,1),
    SOURCE STRING,
    CREATED_AT TIMESTAMP_NTZ
);

-- GOLD: Enriched feedback
CREATE OR REPLACE TABLE CORTEX_FEEDBACK_DB.GOLD.FEEDBACK_ENRICHED (
    FEEDBACK_ID STRING,
    CLEAN_TEXT STRING,
    RATING NUMBER(2,1),
    SOURCE STRING,
    CREATED_AT TIMESTAMP_NTZ,
    SENTIMENT STRING,
    TOPICS ARRAY,
    SUMMARY STRING
);
