-- Step 1: Clean and standardize (Bronze → Silver)
INSERT INTO CORTEX_FEEDBACK_DB.SILVER.FEEDBACK_CLEAN
SELECT
    UUID_STRING() AS FEEDBACK_ID,
    TRIM(LOWER(RAW_TEXT)) AS CLEAN_TEXT,
    RATING,
    SOURCE,
    CREATED_AT
FROM CORTEX_FEEDBACK_DB.BRONZE.FEEDBACK_RAW;

-- Step 2: Enrich using Cortex (Silver → Gold)
INSERT INTO CORTEX_FEEDBACK_DB.GOLD.FEEDBACK_ENRICHED
SELECT
    FEEDBACK_ID,
    CLEAN_TEXT,
    RATING,
    SOURCE,
    CREATED_AT,
    SNOWFLAKE.CORTEX.SENTIMENT(CLEAN_TEXT) AS SENTIMENT,
    SNOWFLAKE.CORTEX.TOPICS(CLEAN_TEXT) AS TOPICS,
    SNOWFLAKE.CORTEX.SUMMARIZE(CLEAN_TEXT) AS SUMMARY
FROM CORTEX_FEEDBACK_DB.SILVER.FEEDBACK_CLEAN;
