-- Sentiment distribution
CREATE OR REPLACE VIEW CORTEX_FEEDBACK_DB.GOLD.VW_SENTIMENT_DISTRIBUTION AS
SELECT
    SENTIMENT,
    COUNT(*) AS COUNT
FROM CORTEX_FEEDBACK_DB.GOLD.FEEDBACK_ENRICHED
GROUP BY SENTIMENT;

-- Daily trends
CREATE OR REPLACE VIEW CORTEX_FEEDBACK_DB.GOLD.VW_DAILY_TRENDS AS
SELECT
    DATE(CREATED_AT) AS DAY,
    COUNT(*) AS TOTAL_FEEDBACK,
    AVG(RATING) AS AVG_RATING
FROM CORTEX_FEEDBACK_DB.GOLD.FEEDBACK_ENRICHED
GROUP BY DAY
ORDER BY DAY;

-- Top topics
CREATE OR REPLACE VIEW CORTEX_FEEDBACK_DB.GOLD.VW_TOP_TOPICS AS
SELECT
    VALUE::STRING AS TOPIC,
    COUNT(*) AS FREQUENCY
FROM CORTEX_FEEDBACK_DB.GOLD.FEEDBACK_ENRICHED,
LATERAL FLATTEN(INPUT => TOPICS)
GROUP BY TOPIC
ORDER BY FREQUENCY DESC;
